[project]
name = "huggingface-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "smolagents[litellm]>=1.18.0",
]
